#!/usr/bin/env bash
# The official Postgres image runs this once, only for an empty PGDATA.
# This file may be sourced by the image entrypoint when not executable.
set -euo pipefail
export LC_ALL=C
: "${POSTGRES_USER:?}" "${POSTGRES_DB:?}" "${AUTHENTICATOR_PASSWORD:?}"
[[ "$POSTGRES_USER" == eink_admin && "$POSTGRES_DB" == eink ]] || {
  echo 'Refusing to initialize an unexpected database or administrator.' >&2
  exit 1
}
[[ "$AUTHENTICATOR_PASSWORD" =~ ^[A-Za-z0-9_-]{40,}$ ]] || {
  echo 'Use a URL-safe authenticator password generated by generate-secrets.py.' >&2
  exit 1
}

# psql reads the secret from its process environment, never from a CLI argument.
psql -X --set ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
\getenv authenticator_password AUTHENTICATOR_PASSWORD
CREATE ROLE eink_authenticator LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'authenticator_password';
CREATE ROLE service_role NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
GRANT service_role TO eink_authenticator;
REVOKE ALL ON DATABASE eink FROM PUBLIC;
GRANT CONNECT ON DATABASE eink TO eink_authenticator;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eink_admin IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eink_admin IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eink_admin IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
CREATE SCHEMA migration_control AUTHORIZATION eink_admin;
REVOKE ALL ON SCHEMA migration_control FROM PUBLIC;
CREATE TABLE migration_control.target_identity (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  application text NOT NULL,
  format_version integer NOT NULL
);
INSERT INTO migration_control.target_identity VALUES (true, 'esp32-eink', 1);
SQL

# Use full filenames, not just numeric prefixes: there are two 002 migrations.
shopt -s nullglob
migrations=(/migrations/*.sql)
[[ ${#migrations[@]} -gt 0 ]] || { echo 'No schema migrations mounted.' >&2; exit 1; }
for migration in "${migrations[@]}"; do
  printf 'Applying %s\n' "${migration##*/}"
  psql -X --set ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --file "$migration"
done

# The official entrypoint runs permissions.sql next, after this bootstrap file.
