/* =========================================================================
   strings.ts — EN / DA i18n strings (translated from data.jsx)
   ========================================================================= */

export const STRINGS = {
  en: {
    locale: "en-GB",
    // brand
    product: "Energy Display",
    tagline: "Control what shows on your wall display",
    // login
    signInGoogle: "Continue with Google",
    signInApple: "Continue with Apple",
    signingIn: "Signing in…",
    loginOr: "or",
    whatIsThis: "What is this?",
    loginFoot: "A configurable e-ink display for Danish energy prices, weather and news.",
    authFailed: "Authentication failed",
    authFailedMsg: "We couldn’t reach the sign-in service. Try again.",
    // nav
    nav: { home: "Dashboard", devices: "Devices", account: "Account", docs: "Documentation" },
    navConfig: "Configure",
    crumbs: { dashboard: "Dashboard", devices: "Devices", account: "Account" } as Record<string, string>,
    menuProfile: "Profile",
    menuSettings: "Settings",
    menuLogout: "Log out",
    signedInAs: "Signed in as",
    // dashboard
    dashTitle: "Dashboard",
    dashSub: "Choose what appears on your display and connect the data it needs.",
    // section: display
    displayTitle: "What to display",
    displayDesc: "Toggle a source on, then set its options. Changes preview instantly.",
    srcEnergy: "Energy price",
    srcEnergyHint: "Spot price from Energinet, updated hourly",
    srcWeather: "Weather",
    srcWeatherHint: "Current conditions from OpenWeatherMap",
    srcNews: "News headlines",
    srcNewsHint: "Top story from your chosen source",
    zone: "Price zone",
    updateEvery: "Updates every 30 min on device",
    location: "Location (lat, lng)",
    locationPh: "55.40, 10.40 (Aalborg)",
    useMyLocation: "Use my location",
    locating: "Locating…",
    contentLang: "Headline language",
    source: "Source",
    save: "Save preferences",
    saving: "Saving…",
    saved: "Preferences saved",
    savedMsg: "Your display updates within 30 min.",
    saveFailed: "Couldn’t save",
    saveFailedMsg: "Connection issue. Try again.",
    retry: "Retry",
    loadingPrefs: "Loading preferences…",
    prefsError: "Couldn’t load preferences",
    // section: api keys
    apiTitle: "API keys & services",
    apiDesc: "Some sources need a free key from the provider.",
    statusConnected: "Connected",
    statusNotConfigured: "Not configured",
    statusInvalid: "Invalid key",
    addKey: "Add key",
    updateKey: "Update",
    removeKey: "Remove",
    apiKeyLabel: "API key",
    getKeyAt: "Get a free key at",
    keyDialogTitle: "Add API key",
    keyDialogText: "Paste your key below. It’s stored encrypted and never shown again in full.",
    keyPh: "Paste your key here",
    keyInvalidLen: "Key looks too short — most keys are 32 characters",
    cancel: "Cancel",
    saveKey: "Save key",
    keySaved: "API key saved",
    keySavedMsg: "Connection verified.",
    keyRemoved: "API key removed",
    // preview
    previewTitle: "Live preview",
    previewSub: "2.13″ e-ink · 250×122 px · 1-bit",
    previewLoading: "Rendering preview…",
    previewError: "Preview unavailable",
    previewErrorMsg: "Enable a source and connect its API key.",
    lastUpdated: "Updated",
    nextRefresh: "Next refresh",
    refreshNow: "Refresh now",
    viewDevice: "Device",
    viewRaw: "Raw buffer",
    nothingOn: "Nothing selected",
    nothingOnMsg: "Turn on a source to see it here.",
    // devices
    devTitle: "My devices",
    devSub: "Displays paired with your account.",
    addDevice: "Add device",
    devEmpty: "No devices yet",
    devEmptyMsg: "Pair your first display to start showing live data on your wall.",
    devEmptyCta: "Set up your first display",
    online: "Online",
    offline: "Offline",
    idle: "Idle",
    lastSeen: "Last seen",
    deviceId: "Device ID",
    license: "License",
    firmware: "Firmware",
    edit: "Edit",
    remove: "Remove",
    copied: "Copied to clipboard",
    removeDeviceTitle: "Remove this device?",
    removeDeviceText: "It will stop receiving updates and must be paired again to reconnect.",
    removeForever: "Remove device",
    addDeviceTitle: "Pair a new display",
    addDeviceText: "Enter the device ID printed on the back of your display, then give it a name.",
    deviceName: "Display name",
    deviceNamePh: "Living room display",
    deviceIdPh: "e.g. ESP-7F3A9C",
    pair: "Pair device",
    pairing: "Pairing…",
    devicePaired: "Device paired",
    loadingDevices: "Loading devices…",
    // account
    accTitle: "Account",
    accSub: "Your profile, plan and usage.",
    profile: "Profile",
    name: "Name",
    email: "Email",
    emailReadonly: "Email is managed by your sign-in provider",
    saveChanges: "Save changes",
    profileSaved: "Profile updated",
    subscription: "Subscription",
    plan: "Plan",
    planFree: "Free",
    apiCalls: "API calls this month",
    devicesUsed: "Devices",
    upgrade: "Upgrade to Pro",
    upgradeSoon: "Pro is coming soon — we’ll email you.",
    dangerZone: "Danger zone",
    deleteAccount: "Delete account",
    deleteAccountText: "This permanently erases your account, devices and preferences. This cannot be undone.",
    deleteForever: "Delete forever",
    typeToConfirm: "Type DELETE to confirm",
    // misc
    show: "Show",
    hide: "Hide",
  },
  da: {
    locale: "da-DK",
    product: "Energidisplay",
    tagline: "Bestem hvad der vises på dit vægdisplay",
    signInGoogle: "Fortsæt med Google",
    signInApple: "Fortsæt med Apple",
    signingIn: "Logger ind…",
    loginOr: "eller",
    whatIsThis: "Hvad er det?",
    loginFoot: "Et e-ink display til danske elpriser, vejr og nyheder.",
    authFailed: "Login mislykkedes",
    authFailedMsg: "Vi kunne ikke nå login-tjenesten. Prøv igen.",
    nav: { home: "Oversigt", devices: "Enheder", account: "Konto", docs: "Dokumentation" },
    navConfig: "Konfigér",
    crumbs: { dashboard: "Oversigt", devices: "Enheder", account: "Konto" } as Record<string, string>,
    menuProfile: "Profil",
    menuSettings: "Indstillinger",
    menuLogout: "Log ud",
    signedInAs: "Logget ind som",
    dashTitle: "Oversigt",
    dashSub: "Vælg hvad der vises på dit display, og forbind de data det skal bruge.",
    displayTitle: "Hvad skal vises",
    displayDesc: "Slå en kilde til, og vælg dens indstillinger. Forhåndsvisning opdateres stråks.",
    srcEnergy: "Elpris",
    srcEnergyHint: "Spotpris fra Energinet, opdateres hver time",
    srcWeather: "Vejr",
    srcWeatherHint: "Aktuelt vejr fra OpenWeatherMap",
    srcNews: "Nyhedsoverskrifter",
    srcNewsHint: "Tophistorie fra din valgte kilde",
    zone: "Prisområde",
    updateEvery: "Opdateres hvert 30. min på enheden",
    location: "Placering (lat, lng)",
    locationPh: "55,40, 10,40 (Aalborg)",
    useMyLocation: "Brug min placering",
    locating: "Finder placering…",
    contentLang: "Sprog for overskrifter",
    source: "Kilde",
    save: "Gem indstillinger",
    saving: "Gemmer…",
    saved: "Indstillinger gemt",
    savedMsg: "Dit display opdateres inden for 30 min.",
    saveFailed: "Kunne ikke gemme",
    saveFailedMsg: "Forbindelsesfejl. Prøv igen.",
    retry: "Prøv igen",
    loadingPrefs: "Indlæser indstillinger…",
    prefsError: "Kunne ikke indlæse indstillinger",
    apiTitle: "API-nøgler & tjenester",
    apiDesc: "Nogle kilder kræver en gratis nøgle fra udbyderen.",
    statusConnected: "Forbundet",
    statusNotConfigured: "Ikke konfigureret",
    statusInvalid: "Ugyldig nøgle",
    addKey: "Tilføj nøgle",
    updateKey: "Opdatér",
    removeKey: "Fjern",
    apiKeyLabel: "API-nøgle",
    getKeyAt: "Hent en gratis nøgle på",
    keyDialogTitle: "Tilføj API-nøgle",
    keyDialogText: "Indsæt din nøgle nedenfor. Den gemmes krypteret og vises aldrig fuldt ud igen.",
    keyPh: "Indsæt din nøgle her",
    keyInvalidLen: "Nøglen ser for kort ud — de fleste nøgler er 32 tegn",
    cancel: "Annullér",
    saveKey: "Gem nøgle",
    keySaved: "API-nøgle gemt",
    keySavedMsg: "Forbindelse bekræftet.",
    keyRemoved: "API-nøgle fjernet",
    previewTitle: "Live forhåndsvisning",
    previewSub: "2,13″ e-ink · 250×122 px · 1-bit",
    previewLoading: "Gengiver forhåndsvisning…",
    previewError: "Forhåndsvisning utilgængelig",
    previewErrorMsg: "Slå en kilde til, og forbind dens API-nøgle.",
    lastUpdated: "Opdateret",
    nextRefresh: "Næste opdatering",
    refreshNow: "Opdatér nu",
    viewDevice: "Enhed",
    viewRaw: "Rå buffer",
    nothingOn: "Intet valgt",
    nothingOnMsg: "Slå en kilde til for at se den her.",
    devTitle: "Mine enheder",
    devSub: "Displays parret med din konto.",
    addDevice: "Tilføj enhed",
    devEmpty: "Ingen enheder endnu",
    devEmptyMsg: "Par dit første display for at vise live data på din væg.",
    devEmptyCta: "Opsæt dit første display",
    online: "Online",
    offline: "Offline",
    idle: "Inaktiv",
    lastSeen: "Sidst set",
    deviceId: "Enheds-ID",
    license: "Licens",
    firmware: "Firmware",
    edit: "Redigér",
    remove: "Fjern",
    copied: "Kopieret",
    removeDeviceTitle: "Fjern denne enhed?",
    removeDeviceText: "Den stopper med at modtage opdateringer og skal parres igen for at tilslutte.",
    removeForever: "Fjern enhed",
    addDeviceTitle: "Par et nyt display",
    addDeviceText: "Indtast enheds-ID'et bag på dit display, og giv det et navn.",
    deviceName: "Visningsnavn",
    deviceNamePh: "Stuens display",
    deviceIdPh: "f.eks. ESP-7F3A9C",
    pair: "Par enhed",
    pairing: "Parrer…",
    devicePaired: "Enhed parret",
    loadingDevices: "Indlæser enheder…",
    accTitle: "Konto",
    accSub: "Din profil, dit abonnement og forbrug.",
    profile: "Profil",
    name: "Navn",
    email: "E-mail",
    emailReadonly: "E-mail styres af din login-udbyder",
    saveChanges: "Gem ændringer",
    profileSaved: "Profil opdateret",
    subscription: "Abonnement",
    plan: "Abonnement",
    planFree: "Gratis",
    apiCalls: "API-kald denne måned",
    devicesUsed: "Enheder",
    upgrade: "Opgradér til Pro",
    upgradeSoon: "Pro kommer snart — vi sender dig en mail.",
    dangerZone: "Farezone",
    deleteAccount: "Slet konto",
    deleteAccountText: "Dette sletter permanent din konto, enheder og indstillinger. Kan ikke fortrydes.",
    deleteForever: "Slet permanent",
    typeToConfirm: "Skriv DELETE for at bekræfte",
    show: "Vis",
    hide: "Skjul",
  },
} as const;

export type Lang = keyof typeof STRINGS;
export type Strings = typeof STRINGS['en'];
