// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/flash": {
    params: {};
  };
  "/sso-callback": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/flash" | "/sso-callback" | "/*";
  };
  "./pages/FlashPage.tsx": {
    id: "pages/FlashPage";
    page: "/flash";
  };
  "./pages/SsoCallback.tsx": {
    id: "pages/SsoCallback";
    page: "/sso-callback";
  };
  "./App.tsx": {
    id: "App";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/FlashPage": typeof import("./src/./pages/FlashPage.tsx");
  "pages/SsoCallback": typeof import("./src/./pages/SsoCallback.tsx");
  "App": typeof import("./src/./App.tsx");
};