/* =========================================================================
   strings.ts — EN / DA i18n strings (translated from data.jsx)
   ========================================================================= */

export const STRINGS = {
  en: {
    locale: "en-GB",
    // brand
    product: "ESP32 Display",
    tagline: "Control what shows on your wall display",
    // login
    signInGoogle: "Continue with Google",
    signInGithub: "Continue with GitHub",
    signingIn: "Signing in…",
    loginOr: "or",
    whatIsThis: "What is this?",
    loginFoot: "A configurable e-ink display for live data, weather and news.",
    authFailed: "Authentication failed",
    authFailedMsg: "We couldn’t reach the sign-in service. Try again.",
    // nav
    nav: { home: "Dashboard", devices: "Devices", firmware: "Firmware", account: "Account", docs: "Documentation", layout: "Layout" },
    navConfig: "Configure",
    crumbs: { dashboard: "Dashboard", devices: "Devices", firmware: "Firmware", account: "Account", layout: "Layout editor" } as Record<string, string>,
    menuProfile: "Profile",
    menuSettings: "Settings",
    menuLogout: "Log out",
    signedInAs: "Signed in as",
    // dashboard
    dashTitle: "Dashboard",
    dashSub: "Choose what appears on your display and connect the data it needs.",
    // section: display
    displayTitle: "What to display",
    displayDesc: "Toggle a source on, then set its options. Changes preview instantly.",
    srcEnergy: "Energy price",
    srcEnergyHint: "Real-time spot price, updated hourly",
    srcWeather: "Weather",
    srcWeatherHint: "Current conditions from OpenWeatherMap",
    srcNews: "News headlines",
    srcNewsHint: "Top story from your chosen source",
    zone: "Price zone",
    updateEvery: "Updates every 30 min on device",
    location: "Location (lat, lng)",
    locationPh: "55.40, 10.40 (Aalborg)",
    useMyLocation: "Use my location",
    locating: "Locating…",
    contentLang: "Headline language",
    source: "Source",
    save: "Save preferences",
    saving: "Saving…",
    saved: "Preferences saved",
    savedMsg: "Your display updates within 30 min.",
    saveFailed: "Couldn’t save",
    saveFailedMsg: "Connection issue. Try again.",
    retry: "Retry",
    loadingPrefs: "Loading preferences…",
    prefsError: "Couldn’t load preferences",
    // section: api keys
    apiTitle: "API keys & services",
    apiDesc: "Some sources need a free key from the provider.",
    statusConnected: "Connected",
    statusNotConfigured: "Not configured",
    statusInvalid: "Invalid key",
    addKey: "Add key",
    updateKey: "Update",
    removeKey: "Remove",
    apiKeyLabel: "API key",
    getKeyAt: "Get a free key at",
    keyDialogTitle: "Add API key",
    keyDialogText: "Paste your key below. It’s stored encrypted and never shown again in full.",
    keyPh: "Paste your key here",
    keyInvalidLen: "Key looks too short — most keys are 32 characters",
    cancel: "Cancel",
    saveKey: "Save key",
    keySaved: "API key saved",
    keySavedMsg: "Connection verified.",
    keyRemoved: "API key removed",
    // preview
    previewTitle: "Live preview",
    previewSub: "2.13″ e-ink · 250×122 px · 1-bit",
    previewLoading: "Rendering preview…",
    previewError: "Preview unavailable",
    previewErrorMsg: "Enable a source and connect its API key.",
    lastUpdated: "Updated",
    nextRefresh: "Next refresh",
    refreshNow: "Refresh now",
    viewDevice: "Device",
    viewRaw: "Raw buffer",
    viewClear: "Clear",
    viewIdeal: "Ideal",
    nothingOn: "Nothing selected",
    nothingOnMsg: "Turn on a source to see it here.",
    // devices
    devTitle: "My devices",
    devSub: "Displays paired with your account.",
    addDevice: "Add device",
    devEmpty: "No devices yet",
    devEmptyMsg: "Pair your first display to start showing live data on your wall.",
    devEmptyCta: "Set up your first display",
    online: "Online",
    offline: "Offline",
    idle: "Idle",
    lastSeen: "Last seen",
    deviceId: "Device ID",
    license: "License",
    firmware: "Firmware",
    edit: "Edit",
    remove: "Remove",
    copied: "Copied to clipboard",
    removeDeviceTitle: "Remove this device?",
    removeDeviceText: "It will stop receiving updates and must be paired again to reconnect.",
    removeForever: "Remove device",
    addDeviceTitle: "Pair a new display",
    addDeviceText: "Enter the device ID printed on the back of your display, then give it a name.",
    deviceName: "Display name",
    deviceNamePh: "Living room display",
    deviceIdPh: "e.g. ESP-7F3A9C",
    pair: "Pair device",
    pairing: "Pairing…",
    devicePaired: "Device paired",
    loadingDevices: "Loading devices…",
    devFetchError: "Couldn't load devices",
    devFetchErrorMsg: "Check your connection and try again.",
    // firmware
    fwTitle: "Firmware updates",
    fwSub: "Manage OTA releases and publish new firmware for your displays.",
    fwVersion: "Version",
    fwActive: "Active",
    fwDownloadPath: "Download path",
    fwChecksum: "Checksum",
    fwCreatedAt: "Published",
    fwNotes: "Release notes",
    fwFormVersion: "Firmware version",
    fwFormDownloadPath: "Binary path",
    fwFormDownloadHint: "Full HTTPS URL to the firmware binary (e.g. https://cdn.example.com/firmware.bin). Required for browser flashing.",
    fwFormChecksum: "Checksum (optional)",
    fwFormNotes: "Release notes",
    fwFormNotesPh: "Short notes about this release",
    fwCreateRelease: "Create release",
    fwVersionCreated: "Firmware release created",
    loadingFirmware: "Loading firmware releases…",
    fwFetchError: "Couldn't load firmware releases",
    fwFetchErrorMsg: "Try again later or check your connection.",
    fwEmpty: "No firmware releases",
    fwEmptyMsg: "Create a firmware release before your device can update.",
    fwCreateFirst: "Create first release",
    fwNone: "None",
    fwDefault: "Default",
    fwDefaultBadge: "System default",
    fwDefaultReady: "Ready to flash",
    fwDefaultNotBuilt: "Not available — set DEFAULT_FIRMWARE_URL in backend .env or build firmware/builds/default.bin",
    // firmware flash assistant
    fwFlashTitle: "Flash device",
    fwFlashSub: "Program your ESP32 directly from this browser via USB.",
    fwFlashSelectVersion: "Select firmware version",
    fwFlashSelectPlaceholder: "Choose a version to flash…",
    fwFlashStep1: "Connect your ESP32 to this computer via a USB cable.",
    fwFlashStep2: "The default firmware is pre-selected. Change the version above if needed.",
    fwFlashStep3: "Click Install, then follow the on-screen prompts.",
    fwFlashBrowserNote: "Requires Chrome or Edge 89+. Firefox and Safari are not supported.",
    fwFlashNoVersions: "No firmware available to flash. Set DEFAULT_FIRMWARE_URL in the backend .env to enable the default firmware.",
    fwFlashManifestLoading: "Loading manifest…",
    fwFlashManifestError: "Could not load the firmware manifest. Check your connection and try again.",
    // account
    accTitle: "Account",
    accSub: "Your profile, plan and usage.",
    profile: "Profile",
    name: "Name",
    email: "Email",
    emailReadonly: "Email is managed by your sign-in provider",
    saveChanges: "Save changes",
    profileSaved: "Profile updated",
    subscription: "Subscription",
    plan: "Plan",
    planFree: "Free",
    apiCalls: "API calls this month",
    devicesUsed: "Devices",
    upgrade: "Upgrade to Pro",
    upgradeSoon: "Pro is coming soon — we’ll email you.",
    dangerZone: "Danger zone",
    deleteAccount: "Delete account",
    deleteAccountText: "This permanently erases your account, devices and preferences. This cannot be undone.",
    deleteForever: "Delete forever",
    typeToConfirm: "Type DELETE to confirm",
    // misc
    show: "Show",
    hide: "Hide",
    loading: "Loading…",
    // theme / connection
    themeLight: "Light mode",
    themeDark: "Dark mode",
    connOnline: "Connection: online (click to simulate offline)",
    connOffline: "Connection: offline (click to restore)",
    toastOnline: "Back online",
    toastOffline: "Offline mode (demo)",
    // devices
    copy: "Copy",
    deviceIdHint: "Printed on the back of your display",
    // preview
    justNow: "just now",
    missingApiKey: "An enabled source is missing its API key and won't show.",
    // display card options
    zoneDK1: "DK1 — West of the Great Belt",
    zoneDK2: "DK2 — East of the Great Belt",
    langDanish: "Dansk",
    langEnglish: "English",
    newsSrcDR: "DR Nyheder",
    newsSrcPolitiken: "Politiken",
    newsSrcTV2: "TV 2",
    // e-ink canvas
    hours24: "24h",
    energyLabel: "POWER",
    nothingSelectedCanvas: "NOTHING SELECTED",
    avgShort: "Avg ",
    weatherConnectKey: "Weather — connect API key",
    wind: "wind",
    newsConnectKey: "News — connect API key",
    montaConnectCred: "Monta — add credentials in API Keys",
    zaptecConnectCred: "Zaptec — add credentials in API Keys",
    // docs page
    docsSub: "Get up and running in seven steps.",
    docsStep1Title: "Install USB driver",
    docsStep1Body: "Most ESP32 boards use a CH340 or CP210x chip. macOS needs a driver from WCH or Silicon Labs; Windows installs it automatically via Windows Update; Linux has it built in.",
    docsStep2Title: "Flash the firmware",
    docsStep2Body: "Go to the Flash page, click Install Firmware, and select the serial port in the browser dialog. Takes about 30 seconds.",
    docsStep3Title: "Connect to the setup hotspot",
    docsStep3Body: "After flashing the device broadcasts a WiFi network called ESP32-Display-XXXXXX. Connect your phone or laptop to it.",
    docsStep4Title: "Enter WiFi credentials",
    docsStep4Body: "A setup page opens automatically. Fill in your home WiFi SSID, password, and backend API URL, then tap Save.",
    docsStep5Title: "Claim your device",
    docsStep5Body: "In the dashboard, go to Devices and enter the device ID to link it to your account.",
    docsStep6Title: "Add API keys",
    docsStep6Body: "Get free keys from OpenWeatherMap and NewsAPI, then paste them on the Account page.",
    docsStep7Title: "Choose what shows",
    docsStep7Body: "Toggle sources in the Dashboard. The display updates within one refresh cycle.",
    docsFlashLink: "Go to Flash page",
    // docs — hardware flashing guide
    docsFlashGuideTitle: "Hardware flashing guide",
    docsFlashGuideSub: "Step-by-step instructions for flashing firmware from your computer via USB.",
    docsFlashBoardElecrow: "Elecrow CrowPanel 2.13\"",
    docsFlashBoardWaveshare: "Waveshare 2.13\" HAT",
    docsFlashOsMac: "macOS",
    docsFlashOsWin: "Windows",
    docsFlashOsArduino: "Arduino IDE",
    docsFlashNoteElecrow: "ESP32-S3 · SSD1680Z · USB-C · CH340/CH343 driver",
    docsFlashNoteWaveshare: "ESP32-WROOM-32 · SSD1680 · USB-A or USB-C · CH340/CP2102 driver",
    docsFlashBootTip: "Upload failing? Hold the BOOT button on the board while clicking Upload, then release it once \"Uploading...\" appears.",
    docsFlashCableTip: "No port detected? The USB cable may be charge-only. Try a different cable that carries data.",
    docsFlashWinDriverTip: "Driver not installing? Right-click the .exe and choose \"Run as administrator\".",
    // auth
    verifyingSession: "Verifying session…",
    welcomeBack: "Welcome back",
    signInSub: "Sign in to manage your e-ink display",
    createAccount: "Create your account",
    createAccountSub: "Get started with your ESP32 Display dashboard",
    // layout editor
    layoutTitle: "Layout editor",
    layoutSub: "Drag and resize widgets to customise your display.",
    layoutSave: "Save layout",
    layoutSaving: "Saving…",
    layoutSaved: "Layout saved",
    layoutSavedMsg: "Your display will update within 30 min.",
    layoutSaveFailed: "Couldn't save layout",
    layoutCancel: "Cancel",
    layoutReset: "Reset to default",
    layoutEditLayout: "Edit layout",
    layoutWidgetEnergy: "Energy price",
    layoutWidgetWeather: "Weather",
    layoutWidgetNews: "News",
    layoutWidgetStatus: "Status bar",
    layoutAvailable: "Available widgets",
    layoutAddWidget: "Add to layout",
    layoutLocked: "Locked",
    // EV integrations — display card
    srcMonta: "Monta EV Charging",
    srcMontaHint: "Live charger status and session data from Monta",
    srcZaptec: "Zaptec EV Charger",
    srcZaptecHint: "Live charger status and session data from Zaptec",
    evFieldChargerStatus: "Charger availability",
    evFieldActiveSession: "Active session (kWh + duration)",
    evFieldTodayStats: "Today's total usage",
    evFieldInstallationInfo: "Installation name",
    evFieldsLabel: "Show on display",
    // EV integrations — credentials
    montaCredTitle: "Monta credentials",
    montaCredDesc: "Enter your Monta API client credentials. Get them from your Monta Operator dashboard.",
    montaClientId: "Client ID",
    montaClientSecret: "Client Secret",
    zaptecCredTitle: "Zaptec credentials",
    zaptecCredDesc: "Enter your Zaptec portal username and password.",
    zaptecUsername: "Username (email)",
    zaptecPassword: "Password",
    evCredSave: "Save credentials",
    evCredSaving: "Saving…",
    evCredSaved: "Credentials saved",
    evCredSavedMsg: "Connection will be verified on next refresh.",
    evCredRemove: "Remove",
    evCredConfigured: "Credentials configured",
    evCredNotConfigured: "Not configured",
  },
  da: {
    locale: "da-DK",
    product: "ESP32 Display",
    tagline: "Bestem hvad der vises på dit vægdisplay",
    signInGoogle: "Fortsæt med Google",
    signInGithub: "Fortsæt med GitHub",
    signingIn: "Logger ind…",
    loginOr: "eller",
    whatIsThis: "Hvad er det?",
    loginFoot: "Et konfigurerbart e-ink display til live data, vejr og nyheder.",
    authFailed: "Login mislykkedes",
    authFailedMsg: "Vi kunne ikke nå login-tjenesten. Prøv igen.",
    nav: { home: "Oversigt", devices: "Enheder", firmware: "Firmware", account: "Konto", docs: "Dokumentation", layout: "Layout" },
    navConfig: "Konfigér",
    crumbs: { dashboard: "Oversigt", devices: "Enheder", firmware: "Firmware", account: "Konto", layout: "Layouteditor" } as Record<string, string>,
    menuProfile: "Profil",
    menuSettings: "Indstillinger",
    menuLogout: "Log ud",
    signedInAs: "Logget ind som",
    dashTitle: "Oversigt",
    dashSub: "Vælg hvad der vises på dit display, og forbind de data det skal bruge.",
    displayTitle: "Hvad skal vises",
    displayDesc: "Slå en kilde til, og vælg dens indstillinger. Forhåndsvisning opdateres stråks.",
    srcEnergy: "Elpris",
    srcEnergyHint: "Realtids-spotpris, opdateres hver time",
    srcWeather: "Vejr",
    srcWeatherHint: "Aktuelt vejr fra OpenWeatherMap",
    srcNews: "Nyhedsoverskrifter",
    srcNewsHint: "Tophistorie fra din valgte kilde",
    zone: "Prisområde",
    updateEvery: "Opdateres hvert 30. min på enheden",
    location: "Placering (lat, lng)",
    locationPh: "55,40, 10,40 (Aalborg)",
    useMyLocation: "Brug min placering",
    locating: "Finder placering…",
    contentLang: "Sprog for overskrifter",
    source: "Kilde",
    save: "Gem indstillinger",
    saving: "Gemmer…",
    saved: "Indstillinger gemt",
    savedMsg: "Dit display opdateres inden for 30 min.",
    saveFailed: "Kunne ikke gemme",
    saveFailedMsg: "Forbindelsesfejl. Prøv igen.",
    retry: "Prøv igen",
    loadingPrefs: "Indlæser indstillinger…",
    prefsError: "Kunne ikke indlæse indstillinger",
    apiTitle: "API-nøgler & tjenester",
    apiDesc: "Nogle kilder kræver en gratis nøgle fra udbyderen.",
    statusConnected: "Forbundet",
    statusNotConfigured: "Ikke konfigureret",
    statusInvalid: "Ugyldig nøgle",
    addKey: "Tilføj nøgle",
    updateKey: "Opdatér",
    removeKey: "Fjern",
    apiKeyLabel: "API-nøgle",
    getKeyAt: "Hent en gratis nøgle på",
    keyDialogTitle: "Tilføj API-nøgle",
    keyDialogText: "Indsæt din nøgle nedenfor. Den gemmes krypteret og vises aldrig fuldt ud igen.",
    keyPh: "Indsæt din nøgle her",
    keyInvalidLen: "Nøglen ser for kort ud — de fleste nøgler er 32 tegn",
    cancel: "Annullér",
    saveKey: "Gem nøgle",
    keySaved: "API-nøgle gemt",
    keySavedMsg: "Forbindelse bekræftet.",
    keyRemoved: "API-nøgle fjernet",
    previewTitle: "Live forhåndsvisning",
    previewSub: "2,13″ e-ink · 250×122 px · 1-bit",
    previewLoading: "Gengiver forhåndsvisning…",
    previewError: "Forhåndsvisning utilgængelig",
    previewErrorMsg: "Slå en kilde til, og forbind dens API-nøgle.",
    lastUpdated: "Opdateret",
    nextRefresh: "Næste opdatering",
    refreshNow: "Opdatér nu",
    viewDevice: "Enhed",
    viewRaw: "Rå buffer",
    viewClear: "Klar",
    viewIdeal: "Ideel",
    nothingOn: "Intet valgt",
    nothingOnMsg: "Slå en kilde til for at se den her.",
    devTitle: "Mine enheder",
    devSub: "Displays parret med din konto.",
    addDevice: "Tilføj enhed",
    devEmpty: "Ingen enheder endnu",
    devEmptyMsg: "Par dit første display for at vise live data på din væg.",
    devEmptyCta: "Opsæt dit første display",
    online: "Online",
    offline: "Offline",
    idle: "Inaktiv",
    lastSeen: "Sidst set",
    deviceId: "Enheds-ID",
    license: "Licens",
    firmware: "Firmware",
    edit: "Redigér",
    remove: "Fjern",
    copied: "Kopieret",
    removeDeviceTitle: "Fjern denne enhed?",
    removeDeviceText: "Den stopper med at modtage opdateringer og skal parres igen for at tilslutte.",
    removeForever: "Fjern enhed",
    addDeviceTitle: "Par et nyt display",
    addDeviceText: "Indtast enheds-ID'et bag på dit display, og giv det et navn.",
    deviceName: "Visningsnavn",
    deviceNamePh: "Stuens display",
    deviceIdPh: "f.eks. ESP-7F3A9C",
    pair: "Par enhed",
    pairing: "Parrer…",
    devicePaired: "Enhed parret",
    loadingDevices: "Indlæser enheder…",
    devFetchError: "Kunne ikke indlæse enheder",
    devFetchErrorMsg: "Tjek din forbindelse og prøv igen.",
    // firmware
    fwTitle: "Firmwareopdateringer",
    fwSub: "Administrer OTA-frigivelser og publicer nyt firmware til dine displays.",
    fwVersion: "Version",
    fwActive: "Aktiv",
    fwDownloadPath: "Downloadsti",
    fwChecksum: "Checksum",
    fwCreatedAt: "Udgivet",
    fwNotes: "Udgivelsesnoter",
    fwFormVersion: "Firmwareversion",
    fwFormDownloadPath: "Binærsti",
    fwFormDownloadHint: "Fuld HTTPS-URL til firmware-binærfilen (fx https://cdn.example.com/firmware.bin). Påkrævet til browser-flashing.",
    fwFormChecksum: "Checksum (valgfrit)",
    fwFormNotes: "Udgivelsesnoter",
    fwFormNotesPh: "Korte noter om denne frigivelse",
    fwCreateRelease: "Opret frigivelse",
    fwVersionCreated: "Firmwarefrigivelse oprettet",
    loadingFirmware: "Indlæser firmwarefrigivelser…",
    fwFetchError: "Kunne ikke indlæse firmwarefrigivelser",
    fwFetchErrorMsg: "Prøv igen senere eller tjek din forbindelse.",
    fwEmpty: "Ingen firmwarefrigivelser",
    fwEmptyMsg: "Opret en firmwarefrigivelse før din enhed kan opdatere.",
    fwCreateFirst: "Opret første frigivelse",
    fwNone: "Ingen",
    fwDefault: "Standard",
    fwDefaultBadge: "Systemstandard",
    fwDefaultReady: "Klar til flash",
    fwDefaultNotBuilt: "Ikke tilgængelig — angiv DEFAULT_FIRMWARE_URL i backend .env eller byg firmware/builds/default.bin",
    // firmware flash assistant
    fwFlashTitle: "Flash enhed",
    fwFlashSub: "Programmér din ESP32 direkte fra denne browser via USB.",
    fwFlashSelectVersion: "Vælg firmwareversion",
    fwFlashSelectPlaceholder: "Vælg en version at flashe…",
    fwFlashStep1: "Tilslut din ESP32 til denne computer via et USB-kabel.",
    fwFlashStep2: "Standard-firmwaren er forvalgt. Skift version ovenfor hvis nødvendigt.",
    fwFlashStep3: "Klik på Install, og følg vejledningen på skærmen.",
    fwFlashBrowserNote: "Kræver Chrome eller Edge 89+. Firefox og Safari understøttes ikke.",
    fwFlashNoVersions: "Ingen firmware tilgængelig. Angiv DEFAULT_FIRMWARE_URL i backend .env for at aktivere standardfirmware.",
    fwFlashManifestLoading: "Indlæser manifest…",
    fwFlashManifestError: "Kunne ikke indlæse firmware-manifest. Tjek din forbindelse og prøv igen.",
    accTitle: "Konto",
    accSub: "Din profil, dit abonnement og forbrug.",
    profile: "Profil",
    name: "Navn",
    email: "E-mail",
    emailReadonly: "E-mail styres af din login-udbyder",
    saveChanges: "Gem ændringer",
    profileSaved: "Profil opdateret",
    subscription: "Abonnement",
    plan: "Abonnement",
    planFree: "Gratis",
    apiCalls: "API-kald denne måned",
    devicesUsed: "Enheder",
    upgrade: "Opgradér til Pro",
    upgradeSoon: "Pro kommer snart — vi sender dig en mail.",
    dangerZone: "Farezone",
    deleteAccount: "Slet konto",
    deleteAccountText: "Dette sletter permanent din konto, enheder og indstillinger. Kan ikke fortrydes.",
    deleteForever: "Slet permanent",
    typeToConfirm: "Skriv DELETE for at bekræfte",
    show: "Vis",
    hide: "Skjul",
    loading: "Indlæser…",
    // theme / connection
    themeLight: "Lystilstand",
    themeDark: "Mørktilstand",
    connOnline: "Forbindelse: online (klik for at simulere offline)",
    connOffline: "Forbindelse: offline (klik for at gendanne)",
    toastOnline: "Tilbage online",
    toastOffline: "Offline-tilstand (demo)",
    // devices
    copy: "Kopiér",
    deviceIdHint: "Står bag på dit display",
    // preview
    justNow: "lige nu",
    missingApiKey: "En valgt kilde mangler sin API-nøgle og vises ikke.",
    // display card options
    zoneDK1: "DK1 — Vest for Storebælt",
    zoneDK2: "DK2 — Øst for Storebælt",
    langDanish: "Dansk",
    langEnglish: "English",
    newsSrcDR: "DR Nyheder",
    newsSrcPolitiken: "Politiken",
    newsSrcTV2: "TV 2",
    // e-ink canvas
    hours24: "24t",
    energyLabel: "ELPRIS",
    nothingSelectedCanvas: "INTET VALGT",
    avgShort: "Gns ",
    weatherConnectKey: "Vejr — forbind API-nøgle",
    wind: "vind",
    newsConnectKey: "Nyheder — forbind API-nøgle",
    montaConnectCred: "Monta — tilføj legitimationsoplysninger",
    zaptecConnectCred: "Zaptec — tilføj legitimationsoplysninger",
    // docs page
    docsSub: "Kom i gang på syv trin.",
    docsStep1Title: "Installer USB-driver",
    docsStep1Body: "De fleste ESP32-kort bruger en CH340- eller CP210x-chip. macOS kræver en driver fra WCH eller Silicon Labs; Windows installerer den automatisk via Windows Update; Linux har den indbygget.",
    docsStep2Title: "Flash firmware",
    docsStep2Body: "Gå til Flash-siden, klik på Installer firmware, og vælg den serielle port i browser-dialogen. Det tager ca. 30 sekunder.",
    docsStep3Title: "Opret forbindelse til opsætnings-hotspot",
    docsStep3Body: "Efter flashning udsender enheden et WiFi-netværk kaldet ESP32-Display-XXXXXX. Tilslut din telefon eller laptop til det.",
    docsStep4Title: "Indtast WiFi-oplysninger",
    docsStep4Body: "En opsætningsside åbnes automatisk. Udfyld dit hjemme-WiFi SSID, adgangskode og backend API-URL, og tryk på Gem.",
    docsStep5Title: "Tilknyt din enhed",
    docsStep5Body: "Gå til Enheder i oversigten, og indtast enheds-ID'et for at koble det til din konto.",
    docsStep6Title: "Tilføj API-nøgler",
    docsStep6Body: "Hent gratis nøgler hos OpenWeatherMap og NewsAPI, og indsæt dem på Konto-siden.",
    docsStep7Title: "Vælg hvad der vises",
    docsStep7Body: "Slå kilder til på oversigten. Displayet opdateres inden for én opdateringscyklus.",
    docsFlashLink: "Gå til Flash-siden",
    // docs — hardware flashing guide (technical content kept in English)
    docsFlashGuideTitle: "Hardware flashing guide",
    docsFlashGuideSub: "Step-by-step instructions for flashing firmware from your computer via USB.",
    docsFlashBoardElecrow: "Elecrow CrowPanel 2.13\"",
    docsFlashBoardWaveshare: "Waveshare 2.13\" HAT",
    docsFlashOsMac: "macOS",
    docsFlashOsWin: "Windows",
    docsFlashOsArduino: "Arduino IDE",
    docsFlashNoteElecrow: "ESP32-S3 · SSD1680Z · USB-C · CH340/CH343 driver",
    docsFlashNoteWaveshare: "ESP32-WROOM-32 · SSD1680 · USB-A eller USB-C · CH340/CP2102 driver",
    docsFlashBootTip: "Upload failing? Hold the BOOT button on the board while clicking Upload, then release it once \"Uploading...\" appears.",
    docsFlashCableTip: "No port detected? The USB cable may be charge-only. Try a different cable that carries data.",
    docsFlashWinDriverTip: "Driver not installing? Right-click the .exe and choose \"Run as administrator\".",
    // auth
    verifyingSession: "Bekræfter session…",
    welcomeBack: "Velkommen tilbage",
    signInSub: "Log ind for at styre dit e-ink display",
    createAccount: "Opret din konto",
    createAccountSub: "Kom i gang med dit ESP32 Display",
    // layout editor
    layoutTitle: "Layouteditor",
    layoutSub: "Træk og ændr størrelse på widgets for at tilpasse dit display.",
    layoutSave: "Gem layout",
    layoutSaving: "Gemmer…",
    layoutSaved: "Layout gemt",
    layoutSavedMsg: "Dit display opdateres inden for 30 min.",
    layoutSaveFailed: "Kunne ikke gemme layout",
    layoutCancel: "Annullér",
    layoutReset: "Nulstil til standard",
    layoutEditLayout: "Rediger layout",
    layoutWidgetEnergy: "Elpris",
    layoutWidgetWeather: "Vejr",
    layoutWidgetNews: "Nyheder",
    layoutWidgetStatus: "Statuslinje",
    layoutAvailable: "Tilgængelige widgets",
    layoutAddWidget: "Tilføj til layout",
    layoutLocked: "Låst",
    // EV integrations — display card
    srcMonta: "Monta EV-opladning",
    srcMontaHint: "Live opladerstatus og sessionsdata fra Monta",
    srcZaptec: "Zaptec EV-oplader",
    srcZaptecHint: "Live opladerstatus og sessionsdata fra Zaptec",
    evFieldChargerStatus: "Opladertilgængelighed",
    evFieldActiveSession: "Aktiv session (kWh + varighed)",
    evFieldTodayStats: "Dagens samlede forbrug",
    evFieldInstallationInfo: "Installationsnavn",
    evFieldsLabel: "Vis på display",
    // EV integrations — credentials
    montaCredTitle: "Monta-legitimationsoplysninger",
    montaCredDesc: "Indtast dine Monta API-klientoplysninger. Hent dem i dit Monta Operator-dashboard.",
    montaClientId: "Klient-ID",
    montaClientSecret: "Klienthemmelighed",
    zaptecCredTitle: "Zaptec-legitimationsoplysninger",
    zaptecCredDesc: "Indtast dit Zaptec portal-brugernavn og din adgangskode.",
    zaptecUsername: "Brugernavn (e-mail)",
    zaptecPassword: "Adgangskode",
    evCredSave: "Gem legitimationsoplysninger",
    evCredSaving: "Gemmer…",
    evCredSaved: "Legitimationsoplysninger gemt",
    evCredSavedMsg: "Forbindelsen verificeres ved næste opdatering.",
    evCredRemove: "Fjern",
    evCredConfigured: "Legitimationsoplysninger konfigureret",
    evCredNotConfigured: "Ikke konfigureret",
  },
} as const;

export type Lang = keyof typeof STRINGS;
export type Strings = typeof STRINGS['en'];
